### PR TITLE
New: option `urls`, .env file; fixes: ESLint 9, expiration test

### LINKED ISSUE #10: Support array of strings as output
Github actions support `array` type. It would be nice to be able to have `urls` output field that is an array of strings = uploaded URLs. Such approach makes it easier to refer to specific URL by index later in workflow. Currently the `url` output field is a single string that requires preprocessing to split it into array - that makes it usable in a real life workflow. Otherwise without conversion to array first - working with `url` is troublesome.

### LINKED ISSUE #12: ESLint 9 issue
When I run command `npm run lint` I get error:
```
ESLint: 9.16.0

ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:

https://eslint.org/docs/latest/use/configure/migration-guide

If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.
```

### LINKED ISSUE #13: Test expiration issue
If expiration is not set during the call, then the resulting expiration will match the expiration option set by user in the Imgg profile. It means it can be zero if auto expiration is not enabled by the user. But if I enable it, then it matches my setting and is not zero. 

```
upload an image using index.js
                                                                                                                                                                                                                                                    
    expect(received).toBe(expected) // Object.is equality                                                                                                                                                                                           
                                                                                                                                                                                                                                                    
    Expected: "0"                                                                                                                                                                                                                                   
    Received: "2678400"                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                    
       98 |   expect(url).toMatch(/https:\/\/i\.ibb\.co\/.*\.png/);                                                                                                                                                                                 
       99 |   const expiration = getValueFromGithubOutput(githubOutputPath, 'expiration');
    > 100 |   expect(expiration.trim()).toBe('0');

```

I will fix it in my PR.

### PR DESCRIPTION
**Pull request by rvalitov**
- fixes #13 
- fixes #10 
- fixes #12 
- supports `.env` file, so it's easy to define the `API_KEY`
- small ESLint fixes
- deleted `node_modules` folder from repository, it's used locally only and should not be committed to GitHub

### CODE REVIEW

**Comment by rvalitov** [comment]
After you merge it, I can share some examples how to use the new `urls` option in workflow.

**Comment by rvalitov** [comment]
BTW do you need to commit the `distr` folder? Perhaps, it should be removed, as it does not contain source code and therefore has no value for being committed?

**Comment by McCzarny** [comment]
I created it a few years ago and I remember that back then it was suggested to commit `node_modules` in a github action repository. I can see that they changed the example repo:
https://github.com/actions/hello-world-javascript-action/issues/12
but it seems that the `dist` dir is still needed.

**Comment by rvalitov** [comment]
Ok, I didn't touch the `dist` folder 😃

**Comment by McCzarny** [comment]
> Let me remove `node_modules` separately to leave only the interesting stuff in this PR.

Done. Please rebase with the current master. Sorry for the inconvenience. Of course you can ignore `dist/` conflicts and simply rebuild the files.

**Comment by rvalitov** [comment]
OK. I will do that later in a few hours...

**Comment by rvalitov** [comment]
@McCzarny ready to merge 😄

**Review by McCzarny — APPROVED** [review]

**Comment by McCzarny** [comment]
Tested locally and seems to work fine.

**Pull request merged**
